experiment:
  id: asinh_10000_huber
  name: "prueba"
  description: "Experimento para reconstrucción de energía y ángulo"
  path: "/home/icantu24/Documents/ARCHES/experiments"

data:
  path: "/home/icantu24/Documents/ARCHES/data/processed/example"
  input_type: "stats"
  output: ["totral_energy"]

model:
  type: mlp
  dropout: 0.0
  batchnorm: True

training:
  epochs: 100
  batch_size: [32]
  
  optimizer:
    type: adam
    lr: 1e-3

  early_stopping:
    enabled: true
    patience: 10

  split:
    train: .70
    validation: .15
    test: .15

  scheduler:
    enabled: false
    type: reduce_on_plateau

search_space:
  layers: [2,4] #hidden layers
  neurons: [32,64,128,512]
  seed: [42]
  activation: ["relu"]

loss:
  type: huber

metrics:
  - energy_res
  - mse
  - R2