experiment:
  id: prueba2_H_1_5_N_16_64_256_pafl_relu_3S_stats_log1p
  name: "prueba"
  description: "Experimento para reconstrucción de energía en escala log1p"
  path: "/home/icantu24/Documents/ARCHES/experiments"

data:
  path: "/home/icantu24/Documents/ARCHES/data/processed/example"
  input_type: "stats"
  scale: "log1p"
  output: ["total_energy"]

model:
  type: mlp
  dropout: 0.0
  batchnorm: False

training:
  epochs: 100
  batch_size: [64]
  
  optimizer:
    type: adam
    lr: 1e-3

  early_stopping:
    enabled: true
    patience: 10

  split:
    train: .70
    validation: .15
    test: .15

  scheduler:
    enabled: false
    type: reduce_on_plateau

search_space:
  layers: [1,3,5] #hidden layers
  neurons: [16,64,256]
  seed: [1]
  activation: ["relu"]  

loss:
  type: pafl

metrics:
  - energy_res
  - mse
  - R2