experiment:
  id: 24
  name: "prueba"
  description: "Experimento para reconstrucción de energía y ángulo"
  path: "/home/icantu24/Documents/ARCHES/experiments"

data:
  path: "/home/icantu24/Documents/ARCHES/data/processed/example"
  input_type: "circle"
  output: ["zenith"]

model:
  type: mlp
  dropout: 0.2
  batchnorm: True

training:
  epochs: 100
  batch_size: [32]
  
  optimizer:
    type: adam
    lr: 1e-3

  early_stopping:
    enabled: true
    patience: 10

  split:
    train: .70
    validation: .15
    test: .15

  scheduler:
    enabled: false
    type: reduce_on_plateau

search_space:
  layers: [2,4] #hidden layers
  neurons: [32,64]
  seed: [42]
  activation: ["tanh"]

loss:
  type: pafl

metrics:
  - energy_res
  - mse
  - R2